import type { IFolder, INote } from "../interface/Data";

export const dummyFolders: IFolder[] = [
	{
		id: "a8f4d2c1b6e7g9h3j0k1",
		title: "Graduation project",
		icon: "code",
		createdAt: "20/08/2024",
		notes: ["nt4", "nt1", "nt3", "nt5"],
	},
	{
		id: "f1e2d3c4b5a6g7h8j9k0",
		title: "Watch Movies",
		icon: "theater_comedy",
		createdAt: "04/09/2024",
		notes: [],
	},
	{
		id: "z9y8x7w6v5u4t3s2r1q0",
		title: "Playing football weekly",
		createdAt: "07/03/2025",
		notes: [],
	},
	{
		id: "n1m2b3v4c5x6z7a8s9d0",
		title: "Buy groceries",
		icon: "shopping_cart",
		createdAt: "15/06/2025",
		notes: [],
	},
	{
		id: "j1k2l3m4n5o6p7q8r9s0",
		title: "Read a new book",
		createdAt: "02/05/2025",
		notes: [],
	},
	{
		id: "q1w2e3r4t5y6u7i8o9p0",
		title: "Call mom",
		icon: "call",
		createdAt: "09/06/2025",
		notes: [],
	},
];

export const dummyNotes: INote[] = [
	{
		id: "nt1",
		title: "Team Standup Meeting",
		createdAt: "12/06/2025",
		type: "task",
		icon: "groups",
		content:
			"<p>Daily standup with dev team to discuss tasks and blockers.</p>",
		date: "16/06/2025",
		time: "09:00 am",
		day: "Monday",
		category: "work",
		status: "ongoing",
		favorite: false,
	},
	{
		id: "nt2",
		title: "Grocery Shopping",
		createdAt: "10/06/2025",
		type: "task",
		icon: "shopping_cart",
		content: "<ul><li>Milk</li><li>Bread</li><li>Eggs</li></ul>",
		date: "18/06/2025",
		time: "06:00 pm",
		day: "Wednesday",
		category: "personal",
		status: "upcoming",
		favorite: true,
	},
	{
		id: "nt3",
		title: "React Hooks Notes",
		createdAt: "09/06/2025",
		type: "note",
		icon: "code",
		content: "<p>Review useEffect, useRef, and useContext with examples.</p>",
		category: "learning",
		favorite: false,
	},
	{
		id: "nt4",
		title: "Doctor Appointment",
		createdAt: "08/06/2025",
		type: "task",
		icon: "local_hospital",
		content: "<p>Annual checkup appointment with Dr. Samir.</p>",
		date: "17/06/2025",
		time: "02:30 pm",
		day: "Tuesday",
		category: "personal",
		status: "upcoming",
		favorite: false,
	},
	{
		id: "nt5",
		title: "Backup Project Files",
		createdAt: "13/06/2025",
		type: "task",
		icon: "cloud_upload",
		content: "<p>Backup all critical project files to Google Drive.</p>",
		date: "14/06/2025",
		time: "11:00 am",
		day: "Saturday",
		category: "work",
		status: "completed",
		favorite: true,
	},
	{
		id: "nt6",
		title: "Football Match Event",
		createdAt: "07/06/2025",
		type: "task",
		icon: "sports_soccer",
		content: "<p>Attend Egypt vs Nigeria match at Cairo Stadium.</p>",
		date: "20/06/2025",
		time: "08:00 pm",
		day: "Friday",
		category: "event",
		status: "upcoming",
		favorite: false,
	},
	{
		id: "nt7",
		title: "SQL Revision Notes",
		createdAt: "11/06/2025",
		type: "note",
		icon: "storage",
		content: "<ul><li>Subqueries</li><li>Joins</li><li>Indexes</li></ul>",
		category: "learning",
		favorite: true,
	},
];
